name: Publish Backend
on:
  push:
    branches:
      - prod

jobs:
  release:
    concurrency:
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd /home/mehmet/TestApi
            git checkout prod
            git pull
            bash start.sh
